
import type { Indicator } from './types';
import { 
  PovertyIcon, 
  HealthIcon, 
  EducationIcon, 
  WaterIcon, 
  EnergyIcon, 
  EconomyIcon,
  IndustryIcon,
  InequalityIcon,
  CityIcon,
  ConsumptionIcon,
  PeaceIcon,
  IncomeIcon
} from './components/Icons';

export const INDICATOR_DATA: Indicator[] = [
  {
    id: 'income',
    name: 'Renda Per Capita',
    description: 'Renda média por habitante, refletindo o poder de compra e qualidade de vida.',
    currentValue: 9500, // Approx. R$48,000 / 5.0 BRL/USD
    targetValue: 50000,
    unit: 'US$',
    formatAsCurrency: true,
    Icon: IncomeIcon,
  },
  {
    id: 'energy_consumption',
    name: 'Consumo de Energia',
    description: 'Consumo de energia per capita, indicando desenvolvimento industrial e acesso.',
    currentValue: 2800,
    targetValue: 10000,
    unit: 'kWh',
    Icon: EnergyIcon,
  },
  {
    id: 'poverty',
    name: 'Erradicação da Pobreza',
    description: 'Índice de progresso na redução da pobreza e vulnerabilidade social.',
    currentValue: 68.5,
    targetValue: 92.0,
    unit: 'pontos',
    Icon: PovertyIcon,
  },
  {
    id: 'health',
    name: 'Saúde e Bem-Estar',
    description: 'Acesso e qualidade dos serviços de saúde para todos os cidadãos.',
    currentValue: 72.1,
    targetValue: 95.0,
    unit: 'pontos',
    Icon: HealthIcon,
  },
  {
    id: 'education',
    name: 'Educação de Qualidade',
    description: 'Qualidade do ensino, infraestrutura escolar e acesso à educação.',
    currentValue: 64.1,
    targetValue: 90.0,
    unit: 'pontos',
    Icon: EducationIcon,
  },
  {
    id: 'water',
    name: 'Água Potável e Saneamento',
    description: 'Disponibilidade e gestão sustentável da água e saneamento.',
    currentValue: 81.3,
    targetValue: 98.0,
    unit: 'pontos',
    Icon: WaterIcon,
  },
  {
    id: 'economy',
    name: 'Trabalho e Crescimento',
    description: 'Promoção do crescimento econômico sustentado e emprego pleno.',
    currentValue: 59.8,
    targetValue: 88.0,
    unit: 'pontos',
    Icon: EconomyIcon,
  },
  {
    id: 'industry',
    name: 'Indústria e Inovação',
    description: 'Infraestrutura resiliente, industrialização inclusiva e fomento à inovação.',
    currentValue: 61.0,
    targetValue: 85.0,
    unit: 'pontos',
    Icon: IndustryIcon,
  },
   {
    id: 'inequality',
    name: 'Redução das Desigualdades',
    description: 'Progresso na redução da desigualdade de renda e oportunidades.',
    currentValue: 55.4,
    targetValue: 82.0,
    unit: 'pontos',
    Icon: InequalityIcon,
  },
  {
    id: 'city',
    name: 'Cidades Sustentáveis',
    description: 'Tornar as cidades inclusivas, seguras, resilientes e sustentáveis.',
    currentValue: 70.2,
    targetValue: 93.0,
    unit: 'pontos',
    Icon: CityIcon,
  },
  {
    id: 'consumption',
    name: 'Consumo Responsável',
    description: 'Assegurar padrões de produção e de consumo sustentáveis.',
    currentValue: 63.7,
    targetValue: 89.0,
    unit: 'pontos',
    Icon: ConsumptionIcon,
  },
  {
    id: 'peace',
    name: 'Paz, Justiça e Instituições',
    description: 'Promover sociedades pacíficas e inclusivas para o desenvolvimento.',
    currentValue: 69.1,
    targetValue: 91.0,
    unit: 'pontos',
    Icon: PeaceIcon,
  },
];
